#!/usr/bin/env bash
# =============================================================================
# omarchy-mac-setup.sh
# One-shot setup for Omarchy on MacBook Pro 2015.
# Run with sudo — writes /etc files and configures system services.
# Safe to re-run; all sections are idempotent.
#
# What this covers:
#
#   1. hid_apple kernel options
#        fnmode=2           → F1-F12 as real function keys (hold Fn for media)
#        swap_opt_cmd=1     → swaps Option/Command pairs:
#                               Left  Option  → Super  (Hyprland mod key)
#                               Left  Command → Alt (left)
#                               Right Command → Alt (right)
#                               Right Option  → Meta (right) ← remapped by XKB below
#        ejectcd_as_delete  → Eject / F13 key becomes Delete
#
#   2. udev hwdb — Fn+Backspace only
#        700a1  Fn+Backspace  → Delete
#        Modifier keys are NOT remapped here; swap_opt_cmd handles them.
#        Mixing hwdb modifier remapping with swap_opt_cmd causes a double-swap.
#
#   3. Hyprland input.lua
#        kb_model = macbook79
#        natural_scroll, clickfinger_behavior (two-finger right-click)
#        kb_options = altwin:ctrl_rwin  (Right Meta → Right Ctrl, replaces keyd)
#
#   4. i3-style keybindings appended to bindings.lua
#
#   5. Workspace window rules appended to hyprland.conf
#        Ferdium → workspace 1
#        kitty   → workspace 2
#        Super+hjkl / Super+Shift+hjkl  focus / swap window
#        Super+q                         close window
#        Super+e                         toggle split
#        Super+r                         resize submap
#        Super+1-0 / Super+Shift+1-0    workspaces 1-10
#
# NOTE (Omarchy Quattro): Hyprland input/keybinding config moved from
# ~/.config/hypr/{input,bindings,looknfeel}.conf to *.lua. The .conf files
# are no longer sourced by hyprland.conf — this script writes to .lua now.
# Window rules (section 5) are unaffected and still live in hyprland.conf.
#
# Usage:
#   chmod +x omarchy-mac-setup.sh
#   sudo ./omarchy-mac-setup.sh
#
# To revert keyboard remapping:
#   sudo rm /etc/modprobe.d/hid_apple.conf /etc/udev/hwdb.d/70-apple-keyboard.hwdb
#   sudo systemd-hwdb update && sudo udevadm trigger
#   sudo mkinitcpio -P && reboot
# =============================================================================

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run with sudo."
  echo "       Usage: sudo $0"
  exit 1
fi

REAL_HOME=$(getent passwd "${SUDO_USER:-$USER}" | cut -d: -f6)

echo "═══════════════════════════════════════════════════════"
echo "  Omarchy MacBook Pro 2015 — one-shot setup"
echo "═══════════════════════════════════════════════════════"

# ── 1. hid_apple kernel options ──────────────────────────────────────────────

echo ""
echo "1/5  hid_apple kernel options..."

cat > /etc/modprobe.d/hid_apple.conf << 'EOF'
# hid_apple options for MacBook Pro 2015 running Linux
# Generated by omarchy-mac-setup.sh

# F1-F12 as real function keys by default (hold Fn for media/brightness)
options hid_apple fnmode=2

# Swap Option and Command on both sides:
#   Left  Option  → Super (Hyprland mod key)
#   Left  Command → Alt (left)
#   Right Command → Alt (right)
#   Right Option  → Meta (right) — further remapped to Ctrl by XKB (step 3)
options hid_apple swap_opt_cmd=1

# Map the Eject key (top-right corner, F13) to Delete
options hid_apple ejectcd_as_delete=1
EOF

echo "   ✓ /etc/modprobe.d/hid_apple.conf"

# Apply swap_opt_cmd and fnmode live so the session doesn't need a reboot
if [[ -w /sys/module/hid_apple/parameters/swap_opt_cmd ]]; then
  echo 1 > /sys/module/hid_apple/parameters/swap_opt_cmd
  echo "   ✓ Applied swap_opt_cmd=1 live"
fi
if [[ -w /sys/module/hid_apple/parameters/fnmode ]]; then
  echo 2 > /sys/module/hid_apple/parameters/fnmode
  echo "   ✓ Applied fnmode=2 live"
fi

# Rebuild initramfs so options are active before the display manager starts
echo "   Rebuilding initramfs (~10 s)..."
mkinitcpio -P 2>&1 | grep -E '^(ERROR|WARNING|==>)' || true
echo "   ✓ initramfs rebuilt"

# ── 2. udev hwdb — Fn+Backspace → Delete only ────────────────────────────────
#
# Modifier keys are intentionally absent here.
# hwdb modifier remapping conflicts with swap_opt_cmd: if both are active,
# swap_opt_cmd sees the already-remapped usage->code and double-swaps the keys.
# swap_opt_cmd handles all modifier remapping; hwdb covers only Fn+Backspace.

echo ""
echo "2/5  udev hwdb (Fn+Backspace → Delete)..."

cat > /etc/udev/hwdb.d/70-apple-keyboard.hwdb << 'EOF'
# MacBook Pro 2015 internal keyboard
# Vendor 05AC = Apple Inc., Product 0273 = Apple Internal Keyboard / Trackpad
#
# Only Fn+Backspace → Delete is mapped here.
# Modifier remapping is handled by hid_apple swap_opt_cmd and XKB.
evdev:input:b0003v05ACp0273*
 KEYBOARD_KEY_700a1=delete
EOF

systemd-hwdb update
udevadm trigger
echo "   ✓ /etc/udev/hwdb.d/70-apple-keyboard.hwdb"

# ── 3. Hyprland input.lua ────────────────────────────────────────────────────

echo ""
echo "3/5  Hyprland input.lua..."

INPUT_LUA="$REAL_HOME/.config/hypr/input.lua"

if [[ -f "$INPUT_LUA" ]]; then
  cp "$INPUT_LUA" "${INPUT_LUA}.bak-mac-$(date +%s)"
fi

cat > "$INPUT_LUA" << 'EOF'
-- Keep only your personal input overrides here. Uncommented settings below
-- replace Omarchy's defaults.
-- Generated by omarchy-mac-setup.sh

-- MacBook Pro 2015 key geometry.
hl.config({
  input = {
    kb_model = "macbook79",
    kb_layout = "us,bg",
    kb_variant = ",phonetic",

    -- altwin:ctrl_rwin maps Right Meta (Right Option after hid_apple swap_opt_cmd) -> Right Ctrl.
    -- grp:ctrl_space_toggle switches between us and bg layouts.
    kb_options = "altwin:ctrl_rwin,grp:ctrl_space_toggle",

    repeat_rate = 40,
    repeat_delay = 250,
    numlock_by_default = true,

    touchpad = {
      natural_scroll = true,
      clickfinger_behavior = true,
      scroll_factor = 0.4,
    },
  },
})
EOF

echo "   ✓ $INPUT_LUA"

# ── 4. i3-style keybindings ──────────────────────────────────────────────────

echo ""
echo "4/5  i3-style keybindings..."

BINDINGS_LUA="$REAL_HOME/.config/hypr/bindings.lua"

if [[ ! -f "$BINDINGS_LUA" ]]; then
  echo "   ✗ $BINDINGS_LUA not found — is Omarchy fully installed?"
  echo "     Re-run this script after first boot into Omarchy."
else
  cp "$BINDINGS_LUA" "${BINDINGS_LUA}.bak-i3-$(date +%s)"

  # Remove any previous i3-compat block (idempotent re-runs)
  if grep -q "-- >>> i3-compat block" "$BINDINGS_LUA"; then
    sed -i '/-- >>> i3-compat block/,/-- <<< i3-compat block/d' "$BINDINGS_LUA"
  fi

  cat >> "$BINDINGS_LUA" << 'BINDINGS'

-- >>> i3-compat block — managed by omarchy-mac-setup.sh; do not edit manually

-- Rebind SUPER ALT+F (was: Full width) to SUPER SHIFT+=
hl.unbind("SUPER + ALT + F")
o.bind("SUPER + SHIFT + equal", "Full width", hl.dsp.window.fullscreen({ mode = "maximized" }))

-- Remap Ctrl+[ to Escape globally (wtype injects a clean Escape with no modifiers)
o.bind("CTRL + bracketleft", "Escape via wtype", "wtype -k escape")

-- Unbind Omarchy defaults that conflict with hjkl navigation
hl.unbind("SUPER + J") -- was: togglesplit       -> use Super+e instead
hl.unbind("SUPER + K") -- was: show key bindings -> use Super+Alt+Space -> Omarchy menu
hl.unbind("SUPER + L") -- was: layout toggle     -> use Super+Alt+Space -> Omarchy menu

-- Focus movement (i3: $mod+hjkl)
o.bind("SUPER + h", "Focus left", hl.dsp.focus({ direction = "l" }))
o.bind("SUPER + j", "Focus down", hl.dsp.focus({ direction = "d" }))
o.bind("SUPER + k", "Focus up", hl.dsp.focus({ direction = "u" }))
o.bind("SUPER + l", "Focus right", hl.dsp.focus({ direction = "r" }))

-- Move/swap windows (i3: $mod+Shift+hjkl)
o.bind("SUPER + SHIFT + h", "Swap window left", hl.dsp.window.swap({ direction = "l" }))
o.bind("SUPER + SHIFT + j", "Swap window down", hl.dsp.window.swap({ direction = "d" }))
o.bind("SUPER + SHIFT + k", "Swap window up", hl.dsp.window.swap({ direction = "u" }))
o.bind("SUPER + SHIFT + l", "Swap window right", hl.dsp.window.swap({ direction = "r" }))

-- Split direction (i3: $mod+v / $mod+b)
o.bind("SUPER + v", "Preselect split down", hl.dsp.exec_raw("layoutmsg", "preselect d"))
o.bind("SUPER + b", "Preselect split right", hl.dsp.exec_raw("layoutmsg", "preselect r"))

-- Toggle split layout (i3: $mod+e)
o.bind("SUPER + e", "Toggle split layout", hl.dsp.layout("togglesplit"))

-- Close window (i3: $mod+Shift+q, mapped to Super+q for comfort)
o.bind("SUPER + q", "Close window", hl.dsp.window.close())

-- Workspaces 1-10 (i3 uses all 10; Omarchy default stops at 4)
local i3_workspace_keys = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "0" }
for index, key in ipairs(i3_workspace_keys) do
  local workspace = tostring(index == 10 and 10 or index)
  o.bind("SUPER + " .. key, "Switch to workspace " .. workspace, hl.dsp.focus({ workspace = workspace }))
  o.bind("SUPER + SHIFT + " .. key, "Move window to workspace " .. workspace, hl.dsp.window.move({ workspace = workspace }))
end

-- Resize submap (i3: $mod+r -> resize mode, Escape/Enter to leave)
hl.define_submap("resize", "reset", function()
  hl.bind("h", hl.dsp.exec_raw("resizeactive", "-40 0"), { repeat_bind = true })
  hl.bind("l", hl.dsp.exec_raw("resizeactive", "40 0"), { repeat_bind = true })
  hl.bind("k", hl.dsp.exec_raw("resizeactive", "0 -40"), { repeat_bind = true })
  hl.bind("j", hl.dsp.exec_raw("resizeactive", "0 40"), { repeat_bind = true })
  hl.bind("left", hl.dsp.exec_raw("resizeactive", "-40 0"), { repeat_bind = true })
  hl.bind("right", hl.dsp.exec_raw("resizeactive", "40 0"), { repeat_bind = true })
  hl.bind("up", hl.dsp.exec_raw("resizeactive", "0 -40"), { repeat_bind = true })
  hl.bind("down", hl.dsp.exec_raw("resizeactive", "0 40"), { repeat_bind = true })
  hl.bind("Return", hl.dsp.submap("reset"), {})
  hl.bind("Escape", hl.dsp.submap("reset"), {})
end)
o.bind("SUPER + r", "Resize mode", hl.dsp.submap("resize"))

-- <<< i3-compat block
BINDINGS

  echo "   ✓ i3-compat block appended to $BINDINGS_LUA"
fi

# ── 5. Workspace window rules ────────────────────────────────────────────────

echo ""
echo "5/5  Workspace window rules..."

HYPRLAND_CONF="$REAL_HOME/.config/hypr/hyprland.conf"

if [[ ! -f "$HYPRLAND_CONF" ]]; then
  echo "   ✗ $HYPRLAND_CONF not found — is Omarchy fully installed?"
  echo "     Re-run this script after first boot into Omarchy."
else
  cp "$HYPRLAND_CONF" "${HYPRLAND_CONF}.bak-workspaces-$(date +%s)"

  # Remove any previous workspace-rules block (idempotent re-runs)
  if grep -q "# >>> workspace-rules block" "$HYPRLAND_CONF"; then
    sed -i '/# >>> workspace-rules block/,/# <<< workspace-rules block/d' "$HYPRLAND_CONF"
  fi

  cat >> "$HYPRLAND_CONF" << 'WORKSPACERULES'

# >>> workspace-rules block — managed by omarchy-mac-setup.sh; do not edit manually
windowrule = workspace 1 silent, match:class ^Ferdium$
windowrule = workspace 2 silent, match:class ^kitty$
# <<< workspace-rules block
WORKSPACERULES

  echo "   ✓ workspace-rules block appended to $HYPRLAND_CONF"
fi

# ── Reload Hyprland ───────────────────────────────────────────────────────────

if command -v hyprctl &>/dev/null; then
  sudo -u "${SUDO_USER:-$USER}" hyprctl reload 2>/dev/null \
    && echo "" && echo "   ✓ Hyprland config reloaded"
fi

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  Done!  Reboot recommended for full effect."
echo "═══════════════════════════════════════════════════════"
echo ""
echo "  Modifier keys (via hid_apple swap_opt_cmd + XKB altwin:ctrl_rwin):"
echo "    Left Option   →  Super (Hyprland mod key)"
echo "    Left Command  →  Alt (left)"
echo "    Right Option  →  Right Ctrl  (XKB: altwin:ctrl_rwin)"
echo "    Right Command →  Right Alt"
echo "    Fn+Backspace  →  Delete"
echo "    Eject / F13   →  Delete"
echo "    F1-F12        →  function keys (Fn for media/brightness)"
echo "    Caps Lock     →  Caps Lock (normal)"
echo ""
echo "  Keyboard layouts:"
echo "    Ctrl+Space          Switch between US and BG Phonetic"
echo ""
echo "  Touchpad:"
echo "    Natural scroll, two-finger click = right-click"
echo ""
echo "  Keybindings:"
echo "    Super+hjkl          Focus direction"
echo "    Super+Shift+hjkl    Swap window"
echo "    Super+q             Close window"
echo "    Super+e             Toggle split"
echo "    Super+r             Resize mode (hjkl/arrows, Enter/Esc to exit)"
echo "    Ctrl+[              Escape (global)"
echo "    Super+1-0           Switch workspace"
echo "    Super+Shift+1-0     Move window to workspace"
echo ""
echo "  Workspace rules:"
echo "    Ferdium             → workspace 1"
echo "    kitty               → workspace 2"
echo "═══════════════════════════════════════════════════════"
