#!/usr/bin/env bash
# =============================================================================
# omarchy-mac-setup.sh
# One-shot setup for Omarchy on MacBook Pro 2015.
# Run with sudo — writes /etc files and configures system services.
# Safe to re-run; all sections are idempotent.
#
# What this covers:
#
#   1. hid_apple kernel options
#        fnmode=2           → F1-F12 as real function keys (hold Fn for media)
#        swap_opt_cmd=1     → swaps Option/Command pairs:
#                               Left  Option  → Super  (Hyprland mod key)
#                               Left  Command → Alt (left)
#                               Right Command → Alt (right)
#                               Right Option  → Meta (right) ← remapped by XKB below
#        ejectcd_as_delete  → Eject / F13 key becomes Delete
#
#   2. udev hwdb — Fn+Backspace only
#        700a1  Fn+Backspace  → Delete
#        Modifier keys are NOT remapped here; swap_opt_cmd handles them.
#        Mixing hwdb modifier remapping with swap_opt_cmd causes a double-swap.
#
#   3. Hyprland input.conf
#        kb_model = macbook79
#        natural_scroll, clickfinger_behavior (two-finger right-click)
#        kb_options = altwin:ctrl_rwin  (Right Meta → Right Ctrl, replaces keyd)
#
#   4. i3-style keybindings appended to bindings.conf
#
#   5. Workspace window rules appended to hyprland.conf
#        Ferdium → workspace 1
#        kitty   → workspace 2
#        Super+hjkl / Super+Shift+hjkl  focus / swap window
#        Super+q                         close window
#        Super+e                         toggle split
#        Super+r                         resize submap
#        Super+1-0 / Super+Shift+1-0    workspaces 1-10
#
# Usage:
#   chmod +x omarchy-mac-setup.sh
#   sudo ./omarchy-mac-setup.sh
#
# To revert keyboard remapping:
#   sudo rm /etc/modprobe.d/hid_apple.conf /etc/udev/hwdb.d/70-apple-keyboard.hwdb
#   sudo systemd-hwdb update && sudo udevadm trigger
#   sudo mkinitcpio -P && reboot
# =============================================================================

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run with sudo."
  echo "       Usage: sudo $0"
  exit 1
fi

REAL_HOME=$(getent passwd "${SUDO_USER:-$USER}" | cut -d: -f6)

echo "═══════════════════════════════════════════════════════"
echo "  Omarchy MacBook Pro 2015 — one-shot setup"
echo "═══════════════════════════════════════════════════════"

# ── 1. hid_apple kernel options ──────────────────────────────────────────────

echo ""
echo "1/5  hid_apple kernel options..."

cat > /etc/modprobe.d/hid_apple.conf << 'EOF'
# hid_apple options for MacBook Pro 2015 running Linux
# Generated by omarchy-mac-setup.sh

# F1-F12 as real function keys by default (hold Fn for media/brightness)
options hid_apple fnmode=2

# Swap Option and Command on both sides:
#   Left  Option  → Super (Hyprland mod key)
#   Left  Command → Alt (left)
#   Right Command → Alt (right)
#   Right Option  → Meta (right) — further remapped to Ctrl by XKB (step 3)
options hid_apple swap_opt_cmd=1

# Map the Eject key (top-right corner, F13) to Delete
options hid_apple ejectcd_as_delete=1
EOF

echo "   ✓ /etc/modprobe.d/hid_apple.conf"

# Apply swap_opt_cmd and fnmode live so the session doesn't need a reboot
if [[ -w /sys/module/hid_apple/parameters/swap_opt_cmd ]]; then
  echo 1 > /sys/module/hid_apple/parameters/swap_opt_cmd
  echo "   ✓ Applied swap_opt_cmd=1 live"
fi
if [[ -w /sys/module/hid_apple/parameters/fnmode ]]; then
  echo 2 > /sys/module/hid_apple/parameters/fnmode
  echo "   ✓ Applied fnmode=2 live"
fi

# Rebuild initramfs so options are active before the display manager starts
echo "   Rebuilding initramfs (~10 s)..."
mkinitcpio -P 2>&1 | grep -E '^(ERROR|WARNING|==>)' || true
echo "   ✓ initramfs rebuilt"

# ── 2. udev hwdb — Fn+Backspace → Delete only ────────────────────────────────
#
# Modifier keys are intentionally absent here.
# hwdb modifier remapping conflicts with swap_opt_cmd: if both are active,
# swap_opt_cmd sees the already-remapped usage->code and double-swaps the keys.
# swap_opt_cmd handles all modifier remapping; hwdb covers only Fn+Backspace.

echo ""
echo "2/5  udev hwdb (Fn+Backspace → Delete)..."

cat > /etc/udev/hwdb.d/70-apple-keyboard.hwdb << 'EOF'
# MacBook Pro 2015 internal keyboard
# Vendor 05AC = Apple Inc., Product 0273 = Apple Internal Keyboard / Trackpad
#
# Only Fn+Backspace → Delete is mapped here.
# Modifier remapping is handled by hid_apple swap_opt_cmd and XKB.
evdev:input:b0003v05ACp0273*
 KEYBOARD_KEY_700a1=delete
EOF

systemd-hwdb update
udevadm trigger
echo "   ✓ /etc/udev/hwdb.d/70-apple-keyboard.hwdb"

# ── 3. Hyprland input.conf ───────────────────────────────────────────────────

echo ""
echo "3/5  Hyprland input.conf..."

INPUT_CONF="$REAL_HOME/.config/hypr/input.conf"

if [[ -f "$INPUT_CONF" ]]; then
  cp "$INPUT_CONF" "${INPUT_CONF}.bak-mac-$(date +%s)"
fi

cat > "$INPUT_CONF" << 'EOF'
# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
    # MacBook Pro 2015 key geometry
    kb_model = macbook79

    kb_layout = us,bg
    kb_variant = ,phonetic

    # altwin:ctrl_rwin maps Right Meta (Right Option after swap_opt_cmd) → Right Ctrl.
    # Using XKB here avoids keyd, which intercepts the bcm5974 trackpad and breaks it.
    # grp:ctrl_space_toggle switches between us and bg layouts.
    kb_options = altwin:ctrl_rwin,grp:ctrl_space_toggle

    # Keyboard repeat
    repeat_rate = 40
    repeat_delay = 250

    numlock_by_default = true

    touchpad {
        # Mac-style (natural) scrolling
        natural_scroll = true

        # Two-finger click = right-click
        clickfinger_behavior = true

        scroll_factor = 0.4
    }
}
EOF

echo "   ✓ $INPUT_CONF"

# ── 4. i3-style keybindings ──────────────────────────────────────────────────

echo ""
echo "4/5  i3-style keybindings..."

BINDINGS_FILE="$REAL_HOME/.config/hypr/bindings.conf"

if [[ ! -f "$BINDINGS_FILE" ]]; then
  echo "   ✗ $BINDINGS_FILE not found — is Omarchy fully installed?"
  echo "     Re-run this script after first boot into Omarchy."
else
  cp "$BINDINGS_FILE" "${BINDINGS_FILE}.bak-i3-$(date +%s)"

  # Remove any previous i3-compat block (idempotent re-runs)
  if grep -q "# >>> i3-compat block" "$BINDINGS_FILE"; then
    sed -i '/# >>> i3-compat block/,/# <<< i3-compat block/d' "$BINDINGS_FILE"
  fi

  cat >> "$BINDINGS_FILE" << 'BINDINGS'

# >>> i3-compat block — managed by omarchy-mac-setup.sh; do not edit manually

# Unbind Omarchy defaults that conflict with hjkl navigation
unbind = SUPER, J   # was: togglesplit       → use Super+e instead
unbind = SUPER, K   # was: show key bindings → use Super+Alt+Space → Omarchy menu
unbind = SUPER, L   # was: layout toggle     → use Super+Alt+Space → Omarchy menu

# Focus movement (i3: $mod+hjkl)
bind = SUPER, h, movefocus, l
bind = SUPER, j, movefocus, d
bind = SUPER, k, movefocus, u
bind = SUPER, l, movefocus, r

# Move/swap windows (i3: $mod+Shift+hjkl)
bind = SUPER SHIFT, h, swapwindow, l
bind = SUPER SHIFT, j, swapwindow, d
bind = SUPER SHIFT, k, swapwindow, u
bind = SUPER SHIFT, l, swapwindow, r

# Split direction (i3: $mod+v / $mod+b)
bind = SUPER, v, layoutmsg, preselect d
bind = SUPER, b, layoutmsg, preselect r

# Toggle split layout (i3: $mod+e)
bind = SUPER, e, layoutmsg, togglesplit

# Close window (i3: $mod+Shift+q, mapped to Super+q for comfort)
bind = SUPER, q, killactive

# Workspaces 1-10 (i3 uses all 10; Omarchy default stops at 4)
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

# Move window to workspaces 1-10 (i3: $mod+Shift+1-0)
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

# Resize submap (i3: $mod+r → resize mode, Escape/Enter to leave)
bind = SUPER, r, submap, resize
submap = resize
  binde = , h,     resizeactive, -40 0
  binde = , l,     resizeactive,  40 0
  binde = , k,     resizeactive, 0 -40
  binde = , j,     resizeactive, 0  40
  binde = , left,  resizeactive, -40 0
  binde = , right, resizeactive,  40 0
  binde = , up,    resizeactive, 0 -40
  binde = , down,  resizeactive, 0  40
  bind  = , Return, submap, reset
  bind  = , Escape, submap, reset
submap = reset

# Ctrl+[ → Escape globally (wtype injects a clean Escape; requires wtype package)
bind = CTRL, bracketleft, exec, wtype -k escape

# <<< i3-compat block

# Rebind SUPER ALT+F (was: Full width) to SUPER SHIFT+=
unbind = SUPER ALT, F
bindd = SUPER SHIFT, equal, Full width, fullscreen, 1
BINDINGS

  echo "   ✓ i3-compat block appended to $BINDINGS_FILE"
fi

# ── 5. Workspace window rules ────────────────────────────────────────────────

echo ""
echo "5/5  Workspace window rules..."

HYPRLAND_CONF="$REAL_HOME/.config/hypr/hyprland.conf"

if [[ ! -f "$HYPRLAND_CONF" ]]; then
  echo "   ✗ $HYPRLAND_CONF not found — is Omarchy fully installed?"
  echo "     Re-run this script after first boot into Omarchy."
else
  cp "$HYPRLAND_CONF" "${HYPRLAND_CONF}.bak-workspaces-$(date +%s)"

  # Remove any previous workspace-rules block (idempotent re-runs)
  if grep -q "# >>> workspace-rules block" "$HYPRLAND_CONF"; then
    sed -i '/# >>> workspace-rules block/,/# <<< workspace-rules block/d' "$HYPRLAND_CONF"
  fi

  cat >> "$HYPRLAND_CONF" << 'WORKSPACERULES'

# >>> workspace-rules block — managed by omarchy-mac-setup.sh; do not edit manually
windowrule = workspace 1 silent, match:class ^Ferdium$
windowrule = workspace 2 silent, match:class ^kitty$
# <<< workspace-rules block
WORKSPACERULES

  echo "   ✓ workspace-rules block appended to $HYPRLAND_CONF"
fi

# ── Reload Hyprland ───────────────────────────────────────────────────────────

if command -v hyprctl &>/dev/null; then
  sudo -u "${SUDO_USER:-$USER}" hyprctl reload 2>/dev/null \
    && echo "" && echo "   ✓ Hyprland config reloaded"
fi

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  Done!  Reboot recommended for full effect."
echo "═══════════════════════════════════════════════════════"
echo ""
echo "  Modifier keys (via hid_apple swap_opt_cmd + XKB altwin:ctrl_rwin):"
echo "    Left Option   →  Super (Hyprland mod key)"
echo "    Left Command  →  Alt (left)"
echo "    Right Option  →  Right Ctrl  (XKB: altwin:ctrl_rwin)"
echo "    Right Command →  Right Alt"
echo "    Fn+Backspace  →  Delete"
echo "    Eject / F13   →  Delete"
echo "    F1-F12        →  function keys (Fn for media/brightness)"
echo "    Caps Lock     →  Caps Lock (normal)"
echo ""
echo "  Keyboard layouts:"
echo "    Ctrl+Space          Switch between US and BG Phonetic"
echo ""
echo "  Touchpad:"
echo "    Natural scroll, two-finger click = right-click"
echo ""
echo "  Keybindings:"
echo "    Super+hjkl          Focus direction"
echo "    Super+Shift+hjkl    Swap window"
echo "    Super+q             Close window"
echo "    Super+e             Toggle split"
echo "    Super+r             Resize mode (hjkl/arrows, Enter/Esc to exit)"
echo "    Ctrl+[              Escape (global)"
echo "    Super+1-0           Switch workspace"
echo "    Super+Shift+1-0     Move window to workspace"
echo ""
echo "  Workspace rules:"
echo "    Ferdium             → workspace 1"
echo "    kitty               → workspace 2"
echo "═══════════════════════════════════════════════════════"
