#!/usr/bin/env bash

source ./scripts/utils.sh

declare -A packages=(
	["elm"]="elm@latest"
	["elm-test"]="elm-test"
)

for package in "${!packages[@]}"; do
	echo "Installing ${packages[$package]}"
	npm i -g -q "${packages[$package]}"
done
