#!/usr/bin/env bash

for folder in ~/.config/nvim ~/.local/state/nvim ~/.local/share/nvim ~/.cache/nvim; do
	rm -rf "$folder.bak" 2>/dev/null

	if [[ -e $folder ]]; then
		mv $folder "$folder.bak"
	fi
done

declare -A packages=(
	["lazygit"]="lazygit"
	["fd"]="fd"
	["prettierd"]="prettierd"
)

installPackages packages

git clone https://github.com/LazyVim/starter ~/.config/nvim

rm -rf ~/.config/nvim/lua ~/.config/nvim/.git
