#!/usr/bin/env bash

set -e

echo "Updating yabai sudoers. Please provide sudo password if needed."
echo "$(whoami) ALL = (root) NOPASSWD: $(which yabai) --load-sa" | sudo tee /private/etc/sudoers.d/yabai > /dev/null

echo "Starting yabai service ..."
brew services start yabai

