# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = uwsm-app -- ~/.config/hypr/auto-nightlight.sh
exec-once = WAYLAND_DISPLAY=$(ls $XDG_RUNTIME_DIR/wayland-* | head -n 1 | xargs basename) wayvnc 0.0.0.0 5900 
