if &compatible
  set nocompatible
endif

" Allow project specific configurations
set exrc
set secure

call plug#begin()

" == NERDTree
Plug 'scrooloose/nerdtree'
let NERDTreeShowHidden=1

" == Colorsheme
Plug 'tomasr/molokai'

" == Git related plugins
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'

" == Buffer Line
" Plug 'bling/vim-bufferline'

" == Lightline
Plug 'itchyny/lightline.vim'
let g:lightline = { 'active': {} }
let g:lightline.active.left = [ ['mode', 'paste'], ['gitbranch', 'readonly', 'filename', 'modified'], [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ] ]
let g:lightline.component_function = { 'gitbranch': 'fugitive#head' }
let g:lightline.separator = { 'left': '', 'right': '' }
let g:lightline.subseparator = { 'left': '', 'right': '' }
let g:lightline.colorscheme = 'powerline'
let g:lightline.tabline = { 'left': [[ 'tabs' ]], 'right': [[ 'close' ]] }

let g:tmuxline_powerline_separators=1

" == Fzf
Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
let g:fzf_command_prefix = 'Fzf'
" disable statusline overriding
let g:fzf_nvim_statusline = 0

if executable('ag')
  let $FZF_DEFAULT_COMMAND = 'ag -g ""'
  let g:ackprg = 'ag --nogroup --nocolor --column'
endif


Plug 'tpope/vim-surround'
Plug 'alvan/vim-closetag'
Plug 'google/vim-searchindex'
Plug 'ntpeters/vim-better-whitespace'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'Olical/vim-enmasse'
Plug 'tpope/vim-sleuth'
Plug 'vim-scripts/BufOnly.vim'
Plug 'jiangmiao/auto-pairs'

" == JavaScript syntax highlighting ==
Plug 'othree/yajs.vim'
Plug 'othree/es.next.syntax.vim'
Plug 'mxw/vim-jsx'
Plug 'othree/javascript-libraries-syntax.vim'

" == Fixmyjs
Plug 'ruanyl/vim-fixmyjs'
let g:fixmyjs_use_local = 1
let g:fixmyjs_rc_local = 1

" == Prettier
Plug 'prettier/vim-prettier', {
  \ 'do': 'npm install',
  \ 'for': ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown'] }
let g:prettier#quickfix_enabled = 0
let g:prettier#autoformat = 0
let g:prettier#config#bracket_spacing = 'true'
let g:prettier#config#trailing_comma = 'all'
" autocmd BufWritePre,TextChanged,InsertLeave *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md PrettierAsync


Plug 'mxw/vim-jsx'
let g:jsx_ext_required = 0

" == NERDCommenter
Plug 'scrooloose/nerdcommenter'
" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1


" == elm
Plug 'elmcast/elm-vim'
let g:elm_format_autosave = 1

" == Rooter
Plug 'airblade/vim-rooter'
let g:rooter_silent_chdir = 1
let g:rooter_patterns = ['.git/', 'package.json', '.git', 'elm.json']

Plug 'terryma/vim-multiple-cursors'
Plug 'airblade/vim-gitgutter'
Plug 'ervandew/supertab'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'zivyangll/git-blame.vim'


Plug 'neovimhaskell/haskell-vim'

" == ALE
" Enable completion where available.
" This setting must be set before ALE is loaded.
let g:ale_completion_enabled = 1

Plug 'w0rp/ale'

let g:ale_linters = {
\   'javascript': ['eslint'],
\}

let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'javascript': ['prettier', 'eslint'],
\   'elm': ['elm-format'],
\}

" Do not lint or fix minified files.
let g:ale_pattern_options = {
\ '\.min\.*$': {'ale_linters': [], 'ale_fixers': []},
\}

let g:ale_lint_on_text_changed = 'never'
let g:ale_fix_on_save = 1
let g:ale_set_highlights = 0

let g:ale_sign_error = "\uf05e"
let g:ale_sign_warning = "\uf071"
let g:ale_sign_info = "\uf05a"


let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_echo_msg_format = '%severity%: %s'

" Write this in your vimrc file
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1

" == ALE lightline
" Plug 'maximbaz/lightline-ale'

" let g:lightline.component_expand = {
      " \  'linter_checking': 'lightline#ale#checking',
      " \  'linter_warnings': 'lightline#ale#warnings',
      " \  'linter_errors': 'lightline#ale#errors',
      " \  'linter_ok': 'lightline#ale#ok',
      " \ }

" let g:lightline#ale#indicator_warnings = "\uf071"
" let g:lightline#ale#indicator_errors = "\uf05e"
" let g:lightline#ale#indicator_info = "\uf05a"
" let g:lightline#ale#indicator_ok = ""

call plug#end()

" Session Management
" automatically load and save session on start/exit.
function! MakeSession()
  if g:sessionfile != ""
    echo "Saving."
    if (filewritable(g:sessiondir) != 2)
      exe 'silent !mkdir -p ' g:sessiondir
      redraw!
    endif
    exe "mksession! " . g:sessionfile
  endif
endfunction

function! LoadSession()
  if argc() == 0
    let g:sessiondir = $HOME . "/.vim/sessions" . getcwd()
    let g:sessionfile = g:sessiondir . "/session.vim"
    if (filereadable(g:sessionfile))
      exe 'source ' g:sessionfile
    else
      echo "No session loaded."
    endif
  else
    let g:sessionfile = ""
    let g:sessiondir = ""
  endif
endfunction

au VimEnter * nested :call LoadSession()
au VimLeave * :call MakeSession()

" Auto-resize splits when vim resizes
au VimResized * wincmd =



set backupdir=~/.vimfiles/backup/
set directory=~/.vimfiles/backup/
set backupcopy=yes
set fileencoding=utf-8
set hidden
set hlsearch
set incsearch
set ignorecase
set smartcase
set nu
set mouse=
set clipboard+=unnamed
set guifont=DroidSansMonoForPowerline\ Nerd\ Font:h12
set backspace=2
" Position splits below and right
set splitright
set splitbelow
set whichwrap+=<,>,h,l,[,]

filetype plugin indent on


" Visual
syntax on
set completeopt=menu
set gcr=a:blinkon1
set tabstop=2
set softtabstop=0
set shiftwidth=2
set autoindent
set expandtab
set visualbell
set t_Co=256
"set termguicolors
colorscheme molokai
highlight ColorColumn ctermbg=darkgrey
highlight Directory ctermfg=grey

" Powerline
set rtp+=$HOME/.local/lib/python2.7/site-packages/powerline/bindings/vim/
set laststatus=2


" == Identation and Spaces
autocmd FileType html,htmldjango,css,scss,less,sass,stylus,json,javascript,coffee setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2 colorcolumn=80
autocmd FileType python setlocal expandtab shiftwidth=4 tabstop=4 softtabstop=4 colorcolumn=80


" == Filetypes
autocmd BufRead,BufNewFile *.jsx,*.ejs set filetype=javascript
autocmd BufRead,BufNewFile *.md,markdown,*.mkd setlocal syntax=markdown
autocmd BufRead,BufNewFile *.json set filetype=json

" == Autoreload file
set autoread
au CursorMoved,CursorHold,FocusGained,BufEnter,InsertEnter * :checkt

" Autochange currdir
autocmd BufEnter * silent! lcd %:p:h

" Highlight current line
set cursorline

" Remember last location in file
au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
      \| exe "normal g'\"" | endif


" Better Whitespace
autocmd FileType sh,css,sass,less,scss,coffee,python,html,javascript,htmldjango,markdown autocmd BufWritePre <buffer> StripWhitespace



" Bindings
let mapleader = "\<space>"
let g:mapleader = "\<space>"
nmap      <silent> <F9> :Gblame<CR>
nmap      <Tab> :b#<CR>
nmap      <silent> <C-j> :+10<CR>
vmap      <silent> <C-j> 10j<CR>
nnoremap  <silent> <C-k> :-10<CR>
vnoremap  <silent> <C-k> 10k<CR>
imap      <silent> jj <ESC>
nnoremap  <silent> <Leader><Leader>s <ESC>:w<CR>
nmap      <silent> <M-w> :bp\|bd#<CR>
nmap      <silent> <M-k> :wincmd k<CR>
nmap      <silent> <M-j> :wincmd j<CR>
nmap      <silent> <M-h> :wincmd h<CR>
nmap      <silent> <M-l> :wincmd l<CR>
nmap      <silent> <M-K> :wincmd K<CR>
nmap      <silent> <M-J> :wincmd J<CR>
nmap      <silent> <M-H> :wincmd H<CR>
nmap      <silent> <M-L> :wincmd L<CR>
nmap      <silent> <Leader><Esc> :noh<CR>
nmap      <silent> <Leader>bd :bufdo bd<CR><CR>
map       <silent> <F3> :NERDTreeToggle<CR>
nmap      <silent> <F2> :NERDTreeFind<CR>
nnoremap  <silent> <C-p> :FzfFiles<CR>
nnoremap  <silent> <C-h> :FzfHistory<CR>
nnoremap  <silent> <Leader>a :FzfAg<CR>
nnoremap  <silent> <Leader>bc :FzfBCommits<CR>
nnoremap  <silent> <Leader>f :Fixmyjs<CR>
nnoremap  <silent> <Leader>= <C-w>=
