add_newline = true
command_timeout = 200
format = "[$directory](green) $git_branch${custom.git_status}[\\$ ](white)"

[character]
disabled = true

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "green"
format = "[$path]($style)"

[git_branch]
format = "[\\(](white)[$branch](bold purple)"
style = "white"

[custom.git_status]
command = "~/.config/starship/modules/git-prompt-status"
when = "git rev-parse --is-inside-work-tree"
format = '$output '

[status]
disabled = false
format = '[\[$status\]]($style)'
style = "red"
success_symbol = ""
